### ISSUE TITLE
Authentication - Backend

### ISSUE THREAD

**Issue by codydaig** [codydaig/911vm#21]
Implement Authentication on the backend. 

My initial thoughts to help guide getting started:
- Use JWT (JSON Web Tokens)
- A "User" is the same as a "Volunteer" in the database so no need to create new nodes.
- It might be easy to just default volunteer passwords to "null" and not allow sign in until a password is set. Maybe through a forgot password? (Open to ideas here)
- Make sure we are hashing passwords with salts. 
- I don't see a need to store tokens in the database at this time. 
- Tokens should expire. 

Let me know if you need any other guidance.

**Comment by mjraybk07** [comment]
We added a PR for user sign up https://github.com/codydaig/911vm/pull/22

TODO: We will follow with user sign in, and then middleware to protect /authorize / authenticate transactions

**Comment by mjraybk07** [comment]
We added a PR#24 which incorporates and replaces PR#23. It adds the user login api and protect / authorization middleware https://github.com/codydaig/911vm/pull/24

This completes our submissions for the above issue and features
